name: Run tests upon Flux update

on:
  repository_dispatch:
    types: [flux-updated]

jobs:
  show-version:
    runs-on: ubuntu-latest
    steps:
      - name: Print Image Tag
        run: |
          echo "ğŸ›°ï¸Flux will deploy image with tag: ${{ github.event.client_payload.image_tag || 'UNKNOWN' }}"
